import type { Metadata } from "next";
import "./globals.css";
import appbg from '../assets/appbg.png'; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden" >
        <div className="relative ">
          <img className="w-[100dvw] h-[100dvh]  absolute top-0 left-0 z-[-1]" src={appbg.src} alt="" />
          {children}
        </div>
      </body>
    </html>
  );
}
